version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt || true 
  build:
    commands:
      - echo Running test...
      - python -m unittest test_app.py

artifacts:
  files:
    - '**/*'
